StoryMaps: The US Military on (and off) the Oregon Trail
HUM-331-Princeton/HUM-331-Princeton.github.io pull request #55
Opened 2021-03-09 04:33 UTC by hopem8

Hi Professor Reynolds,

I hope you enjoy reading about this! And I hope that all of the HTML code goes through!

Thanks so much.

Best,
Hope Perry

2021-03-10 21:59 UTC, melissabreynolds requested changes
Hope,

You have done a wonderful job with the contextual research for your final project, and your execution of the StoryMap was spot on. I also really appreciate the conversational and playful, but still informative, nature of your writing here. You've struck just the right tone for an academic blog post. 

I've requested just a few very minor edits to your post which you should be able to take care of in just a few minutes. The one major issue is that the single quotes around your embed code mean that as it is, Jekyll won't render the HTML into your beautiful StoryMap. Remove those single quotation marks, and then it should work correctly.

I really look forward to seeing what you and Sophie come up with for your final project. You both have really dug in to your research, and I think there are such interesting connections between your two sources.

Grade: A

Once you make these minor edits, let me know if you feel comfortable with me sending this post to the site.

2021-03-10 21:59 UTC, melissabreynolds commented on _posts/2021-03-08-US-Military-Oregon-Trail.md
> +## The US Military on (and off) the Oregon Trail
For future reference, you don't need to add your title here. The "title" element in the header will tell the Jekyll convertor to make that the title of the post. As it is, this will render with the same text twice in a row.

2021-03-10 21:59 UTC, melissabreynolds commented on _posts/2021-03-08-US-Military-Oregon-Trail.md
> +I was excited to begin this digital tools assignment because of the StoryMaps format, and I was happy to start delving into the 19th century American West. I decided that for this project I wanted to
To insert the hyperlink to your previous post, don't include the backslash or the quotation marks. Just the URL in parentheses.

2021-03-10 21:59 UTC, melissabreynolds commented on _posts/2021-03-08-US-Military-Oregon-Trail.md
> +`<iframe src="https://uploads.knightlab.com/storymapjs/cc419bf9196033c361e580670bcbcb51/outwest/index.html" frameborder="0" width="100%" height="800"></iframe>`
This is important! Remove the single apostrophe before and after the embed code. Otherwise you'll just see the code, and not your beautiful story map!

2021-03-10 21:59 UTC, melissabreynolds commented on _posts/2021-03-08-US-Military-Oregon-Trail.md
> +Bagley, Will. “Fort Bridger | WyoHistory.Org.” Accessed March 7, 2021. https://www.wyohistory.org/encyclopedia/fort-bridger. Image from here, via the Wyoming State Museum.
I realized when running your post through a local server that all of these | symbols in website titles is a disaster in Markdown! The reason is that | is used as the symbol to indicate divisions within a table, and so Jekyll adds lots of spaces between words when | appears. Would you mind editing these citations to convert any instances of | to - ?

2021-03-10 22:49 UTC, hopem8 commented on _posts/2021-03-08-US-Military-Oregon-Trail.md
> +Bagley, Will. “Fort Bridger | WyoHistory.Org.” Accessed March 7, 2021. https://www.wyohistory.org/encyclopedia/fort-bridger. Image from here, via the Wyoming State Museum.
Hi Professor Reynolds, thanks so much! I made the changes, so it should be ready to post. Let me know if anything else needs to be tweaked.

Thank you!

Hope

2021-03-11 14:24 UTC, melissabreynolds approved these changes

2021-03-11 14:24 UTC, merged