Savannah Pobre - Digital Tools Assignment 3
HUM-331-Princeton/HUM-331-Princeton.github.io pull request #62
Opened 2021-03-29 23:59 UTC by savannahpobre

2021-03-31 16:10 UTC, melissabreynolds requested changes
Savannah,

You've done a nice job reflecting on the difficulties of conveying the physical attributes of a newspaper page within XML structure. You're right that the contents of a newspaper don't require as much deep thinking about interpretive categories, but the spatial representation of a paper is hard. The newspaper section you chose didn't allow you to think through how you might help a reader access elements of a newspaper not readily accessible in typical metadata, and it would have been nice to see how you might have tried to relate something of the student experience in XML markup.

There are just a couple of minor changes I'd like you to made to the post before I merge it to the site: change "html" in lines 14 and 51 to "xml." In addition, you'll need to add the `excerpt_separator` to your header if you want the excerpt of the post on our homepage to break where you've put the separator here. Be sure the separator tag `<!--continues-->` or `<!--more-->` (whichever you designate in your header) is outside the triple tick marks denoting where your code stops.

Grade: B+

2021-03-31 16:10 UTC, melissabreynolds commented on _posts/2021-03-29-DailyPrinceTEIMarkup.md
> +```html
Same here! xml rather than html.

2021-03-31 16:10 UTC, melissabreynolds commented on _posts/2021-03-29-DailyPrinceTEIMarkup.md
> +<p><i>COACH THOMPSON '88 </i > Leads <tm>Tigers</tm> to <br>Ivy League</br> <sp>championship</sp> and gets it right when noting, “I think that cupboard wasn’t as bare as you thought it was.” </p>
Remove the space between 88 and the end of your tag and the space between i and the >.

2021-03-31 16:10 UTC, melissabreynolds commented on _posts/2021-03-29-DailyPrinceTEIMarkup.md
> +<!-- continues... →
You're going to want to delete this `<!--continues-->` from your post since you don't have an `excerpt_separator: <!--continues-->` anywhere in your header. Or, if you do want the post to break here, be sure to add it to the header and take `<!--continues-->` out of the triple tick marks.

2021-03-31 16:10 UTC, melissabreynolds commented on _posts/2021-03-29-DailyPrinceTEIMarkup.md
> +```html
This should probably be xml rather than html, since we're not using html here

2021-03-31 16:10 UTC, melissabreynolds commented on _posts/2021-03-29-DailyPrinceTEIMarkup.md
> +<p><i>COACH THOMPSON '88 </i > Leads <tm>Tigers</tm> to <br>Ivy League</br> <sp>championship</sp> and gets it right when noting, “I think that cupboard wasn’t as bare as you thought it was.” </p>
If this were a real XML project, you would want to be extra sure that you had no spaces between the content of your text and your tags, as you do in a couple of spots here. The point of your markup is to allow a computer program to return any text between brackets as units of data, and if you have spaces between your text and brackets, those spaces mean you would have two different units of data. For example, below you tag Dick Spies with `<nm>Dick Spies </nm>`. Let's imagine you've encoded lots of newspapers and you want to see how many times Dick Spies shows up. With this tag, a computer would return both "Dick Spies" as a name, and "Dick Spies " as a name.

2021-03-31 16:10 UTC, melissabreynolds commented on _posts/2021-03-29-DailyPrinceTEIMarkup.md
> +<p><i><pl>NEW JERSEY</pl></i> <wthr>Forecasts</wthr> of <ms>two to three feet</ms> of snow for the <pl>Garden State</pl> fail to materialize. <sar>Seems even <wthr>blizzards</wthr> like to avoid the
Would you want to wrap this entire forecast in the `<wthr` tag? Isn't it all weather? Like `<wthr>Forecasts of <ms>two to three feet</ms> of snow</wthr>`?

2021-03-31 16:10 UTC, melissabreynolds commented on _posts/2021-03-29-DailyPrinceTEIMarkup.md
> +<p>Categorizing this document should be relatively simple because it is a periodical or newspaper that showcases events and daily life for members of the Princeton community within the duration of a
This is a good reflection on how the physical presentation of a newspaper sort of eschews the kind of hierarchy you might see in another kind of document.

2021-03-31 16:10 UTC, melissabreynolds commented on _posts/2021-03-29-DailyPrinceTEIMarkup.md
> +<p>Throughout this process I had a few questions regarding how markup was utilized for Digital Humanity scholars to decide what makes it into the TEI code repository. For example when I was writing u
That's where the Text Encoding Initiative comes in! Though I didn't require you all to adhere to its standards, the idea behind it is that there are uniform tags for a variety of objects. A real XML project would begin by determining the tag sets that best apply to their particular document. Others can be added as needed, but the general structure of the code is standardized according to whether you're working with a manuscript, a letter, a play, a novel, a newspaper, etc. And you're right, presenting a newspaper in XML so that all the elements of the page are spatially aligned where they appear on the original page would be quite a challenge--I suspect that's one of many reasons why there aren't many XML projects with newspapers.

2021-04-05 18:54 UTC, savannahpobre commented
Professor Reynolds,

Thank you for all of the feedback and sorry for the late response! I do
wish I had more time to give this assignment in order to format different
aspects of the newspaper, the week definitely got the better of me. I
completely agree with all of your comments!

I believe I was able to go in and commit the changes you suggested so
please feel free to post it on the course site.

Best,
Savannah

On Wed, Mar 31, 2021 at 12:10 PM Melissa Reynolds ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Savannah,
>
> You've done a nice job reflecting on the difficulties of conveying the
> physical attributes of a newspaper page within XML structure. You're right
> that the contents of a newspaper don't require as much deep thinking about
> interpretive categories, but the spatial representation of a paper is hard.
> The newspaper section you chose didn't allow you to think through how you
> might help a reader access elements of a newspaper not readily accessible
> in typical metadata, and it would have been nice to see how you might have
> tried to relate something of the student experience in XML markup.
>
> There are just a couple of minor changes I'd like you to made to the post
> before I merge it to the site: change "html" in lines 14 and 51 to "xml."
> In addition, you'll need to add the excerpt_separator to your header if
> you want the excerpt of the post on our homepage to break where you've put
> the separator here. Be sure the separator tag <!--continues--> or
> <!--more--> (whichever you designate in your header) is outside the
> triple tick marks denoting where your code stops.
>
> Grade: B+
> ------------------------------
>
> In _posts/2021-03-29-DailyPrinceTEIMarkup.md
> <https://github.com/HUM-331-Princeton/HUM-331-Princeton.github.io/pull/62#discussion_r605000110>
> :
>
> > +<ad/>
>
> +<ad/>
>
> +<ad/>
>
> +<div1 type="nameplate">
>
> +<pb/>
>
> +<head><i>THE DAILY</i> PRINCETONIAN</head>
>
> +<ab><num type="volume" value="CXXV No.26">Vol. CXXV, No.26</num>
>
> +<nm type="place">Princeton, New Jersey</nm>,
>
> +<date value="2001-03-01">Friday, March 9, 2001</date>
>
> +<date value="2001">copyright</date>
>
> +<num type="cost" value="30">30 cents</num></ab>
>
> +</div1>
>
> +```
>
> +
>
> +### The Daily Princetonian Column
>
> +```html
>
>
> Same here! xml rather than html.
> ------------------------------
>
> In _posts/2021-03-29-DailyPrinceTEIMarkup.md
> <https://github.com/HUM-331-Princeton/HUM-331-Princeton.github.io/pull/62#discussion_r605001363>
> :
>
> > +<ab><num type="volume" value="CXXV No.26">Vol. CXXV, No.26</num>
>
> +<nm type="place">Princeton, New Jersey</nm>,
>
> +<date value="2001-03-01">Friday, March 9, 2001</date>
>
> +<date value="2001">copyright</date>
>
> +<num type="cost" value="30">30 cents</num></ab>
>
> +</div1>
>
> +```
>
> +
>
> +### The Daily Princetonian Column
>
> +```html
>
> +<div1 type="weekly wrap-up">
>
> +<head><i>Weekly Wrap-Up</i></head>
>
> +<div2 type="dean’s list">
>
> +<head>Dean’s List</head>
>
> +<emjup></emjup>
>
> +<p><i>COACH THOMPSON '88 </i > Leads <tm>Tigers</tm> to <br>Ivy League</br> <sp>championship</sp> and gets it right when noting, “I think that cupboard wasn’t as bare as you thought it was.” </p>
>
>
> Remove the space between 88 and the end of your tag and the space between
> i and the >.
> ------------------------------
>
> In _posts/2021-03-29-DailyPrinceTEIMarkup.md
> <https://github.com/HUM-331-Princeton/HUM-331-Princeton.github.io/pull/62#discussion_r605002881>
> :
>
> > +<head><i>Weekly Wrap-Up</i></head>
>
> +<div2 type="dean’s list">
>
> +<head>Dean’s List</head>
>
> +<emjup></emjup>
>
> +<p><i>COACH THOMPSON '88 </i > Leads <tm>Tigers</tm> to <br>Ivy League</br> <sp>championship</sp> and gets it right when noting, “I think that cupboard wasn’t as bare as you thought it was.” </p>
>
> +<emjup></emjup>
>
> +<p><i>UNIVERSITY WORKERS</i> <ttl>Vice president</ttl> <nm>Dick Spies </nm><yr>GS ‘72</yr> responds to concerns, promising to look into employment and compensation policies. </p>
>
> +</div2>
>
> +<div3 type="dean’s warning">
>
> +<emjdwn></emjdwn>
>
> +<p><i><tm>QUAKERS</tm></i> Heavy pre-season favorites to win the <br>Ivy League</br>, <schl>Penn</schl>was mauled by <schl>Princeton</schl> twice en route to a disappointing record. </p>
>
> +<emjdwn></emjdwn>
>
> +<p><i><pl>NEW JERSEY</pl></i> <wthr>Forecasts</wthr> of <ms>two to three feet</ms> of snow for the <pl>Garden State</pl> fail to materialize. <sar>Seems even <wthr>blizzards</wthr> like to avoid the armpitof <pl>America</pl>.</sar> </p>
>
> +</div3>
>
> +</div1>
>
> +<!-- continues... →
>
>
> You're going to want to delete this <!--continues--> from your post since
> you don't have an excerpt_separator: <!--continues--> anywhere in your
> header. Or, if you do want the post to break here, be sure to add it to the
> header and take <!--continues--> out of the triple tick marks.
> ------------------------------
>
> In _posts/2021-03-29-DailyPrinceTEIMarkup.md
> <https://github.com/HUM-331-Princeton/HUM-331-Princeton.github.io/pull/62#discussion_r605009335>
> :
>
> > @@ -0,0 +1,82 @@
>
> +---
>
> +layout: post
>
> +author: Savannah Pobre
>
> +title: The Daily Princeton March 9th, 2001 TEI Markup
>
> +---
>
> +
>
> +## The Document
>
> +[Daily Princetonian][1], Volume 125, Number 26, 9 March 2001
>
> +
>
> +
>
> +
>
> +## TEI Markup
>
> +### The Daily Princetonian Header
>
> +```html
>
>
> This should probably be xml rather than html, since we're not using html
> here
> ------------------------------
>
> In _posts/2021-03-29-DailyPrinceTEIMarkup.md
> <https://github.com/HUM-331-Princeton/HUM-331-Princeton.github.io/pull/62#discussion_r605014148>
> :
>
> > +<ab><num type="volume" value="CXXV No.26">Vol. CXXV, No.26</num>
>
> +<nm type="place">Princeton, New Jersey</nm>,
>
> +<date value="2001-03-01">Friday, March 9, 2001</date>
>
> +<date value="2001">copyright</date>
>
> +<num type="cost" value="30">30 cents</num></ab>
>
> +</div1>
>
> +```
>
> +
>
> +### The Daily Princetonian Column
>
> +```html
>
> +<div1 type="weekly wrap-up">
>
> +<head><i>Weekly Wrap-Up</i></head>
>
> +<div2 type="dean’s list">
>
> +<head>Dean’s List</head>
>
> +<emjup></emjup>
>
> +<p><i>COACH THOMPSON '88 </i > Leads <tm>Tigers</tm> to <br>Ivy League</br> <sp>championship</sp> and gets it right when noting, “I think that cupboard wasn’t as bare as you thought it was.” </p>
>
>
> If this were a real XML project, you would want to be extra sure that you
> had no spaces between the content of your text and your tags, as you do in
> a couple of spots here. The point of your markup is to allow a computer
> program to return any text between brackets as units of data, and if you
> have spaces between your text and brackets, those spaces mean you would
> have two different units of data. For example, below you tag Dick Spies
> with <nm>Dick Spies </nm>. Let's imagine you've encoded lots of
> newspapers and you want to see how many times Dick Spies shows up. With
> this tag, a computer would return both "Dick Spies" as a name, and "Dick
> Spies " as a name.
> ------------------------------
>
> In _posts/2021-03-29-DailyPrinceTEIMarkup.md
> <https://github.com/HUM-331-Princeton/HUM-331-Princeton.github.io/pull/62#discussion_r605015435>
> :
>
> > +### The Daily Princetonian Column
>
> +```html
>
> +<div1 type="weekly wrap-up">
>
> +<head><i>Weekly Wrap-Up</i></head>
>
> +<div2 type="dean’s list">
>
> +<head>Dean’s List</head>
>
> +<emjup></emjup>
>
> +<p><i>COACH THOMPSON '88 </i > Leads <tm>Tigers</tm> to <br>Ivy League</br> <sp>championship</sp> and gets it right when noting, “I think that cupboard wasn’t as bare as you thought it was.” </p>
>
> +<emjup></emjup>
>
> +<p><i>UNIVERSITY WORKERS</i> <ttl>Vice president</ttl> <nm>Dick Spies </nm><yr>GS ‘72</yr> responds to concerns, promising to look into employment and compensation policies. </p>
>
> +</div2>
>
> +<div3 type="dean’s warning">
>
> +<emjdwn>< [...]

2021-04-06 12:07 UTC, melissabreynolds approved these changes

2021-04-06 12:07 UTC, merged