Paul louis digital tools 3
HUM-331-Princeton/HUM-331-Princeton.github.io pull request #64
Opened 2021-03-30 00:56 UTC by p-biondi

2021-03-31 15:21 UTC, melissabreynolds requested changes
Paul-Louis,

I like that you have paid a lot of attention to how you might encode the structure of power inherent in activist documents like this open letter. Your attention to separating out those affected by policies from those within positions of authority to mitigate those affects is a really powerful way of thinking about what XML could do for a study of activism. However, a clearer hierarchy in terms of your XML would make your XML far more useable for a future researcher. XML isn't just about annotating your particular interpretation of a document--though of course in some sense it will always reflect the interests of whomever develops the tagging structure. But beyond creating tags that reflect what interests _you_ about this document, a good markup hierarchy also thinks about how the data rendered by the markup will be comprehensible as an organizational system. A future researcher can't reuse the same data set (like this marked-up letter) if the parameters that define how the data was harvested in the first place aren't super clear. 

I counted 25 individual tags used in this one document--which is a lot!--and that means if you were to run an XSLT sheet on these tags, a computer would spit out 25 different categories of data, most of which are siblings of one another--meaning that their relationship to one another isn't structured into your schema. A researcher would need to try to intuit why some places are organizations and others are bodies; why sometimes groups are persons and other times they aren't; how authority and institution are two different categories that account for power. Your markup also creates divisions within the corpus of data that might be harvested from this letter when those divisions aren't necessary. For example, there's no need to create a new `<demand1>` then `<demand2>` tag for each demand. You would want a computer to be able to generate _all_ the demands of a particular student organization, right? In which case, you would use `<demand number="1">` if you wanted to order them. Or you might simply tag all of them with `<demand>` and you could simply see, visually, that there were four demands in this letter. 

Thinking about markup both qualitatively and quantitatively is tricky--combining your desire to render your interpretation visible while also thinking through how your interpretive data can be used by others in the future is _the_ major challenge of TEI/XML. If you have questions about these comments or want to talk more, I'm happy to, though for the purposes of my course I simply wanted you all to get a feel for the difficulties of thinking interpretively and structurally at the same time, and we won't be doing future work with XML. Though it is good to know as you work with critical editions that have been created with XML in the future that these are the questions researchers are dealing with all the time!

Grade: B

Before I can merge your post to the site, I need you to make a couple of corrections to the post: you need to remove the repeated section of code from line 124 through line 169 and you also need to edit the file name of your post so that it follows the file-naming conventions for the blog: YYYY-MM-DD-Title.md. It would also be a good idea for you to add an excerpt separator before the section with your code: `<!--more-->`. Otherwise the entire post shows up on the blog feed on our home page.

2021-03-31 15:21 UTC, melissabreynolds commented on _posts/QueerGraduateCaucus.md
> +			<dialogue> response</dialogue> from the
If this were a real XML project to markup this document for harvesting data, you would want to be sure to remove spaces between tags and words. As this is typed now, <dialogue> response</dialogue> would render " response" as a piece of data separate from "response."

2021-03-31 15:21 UTC, melissabreynolds commented on _posts/QueerGraduateCaucus.md
> +			<place> New York City</place>. In the state of
Same thing here! You would want to remove that space between the tag and New York City.

2021-03-31 15:21 UTC, melissabreynolds commented on _posts/QueerGraduateCaucus.md
> +			<resource>affordable</resource> housing off campus. Therefore, we consider it paramount that the
Would it better to tag "affordable housing" rather than just "affordable" since the resource at stake here is housing?

2021-03-31 15:21 UTC, melissabreynolds commented on _posts/QueerGraduateCaucus.md
> +				<institution>University's</institution> housing administration
Here I would also suggest tagging only University like so: `<institution>University</institution>'s` so that the data unit rendered is just University. Otherwise, if you were running a list of all `<institution>`s tagged in the document, you'd get both University and University's as a result.

2021-03-31 15:21 UTC, melissabreynolds commented on _posts/QueerGraduateCaucus.md
> +			<resource>affordable</resource>
Here I think I would nest tags like so `<resource>affordable<aid>on-campus housing</aid></resource>`

2021-03-31 15:21 UTC, melissabreynolds commented on _posts/QueerGraduateCaucus.md
> +		</demand1>
I think you've repeated this whole section of the original letter here. Am I correct that this paragraph does not appear twice in the original letter? If so:

- [ ] Please remove the repeated section of code beginning at line 124 and running to line 169.

2021-03-31 15:21 UTC, melissabreynolds commented on _posts/QueerGraduateCaucus.md
> +				<institution>Princeton's</institution> Student Health Plan
Again, it would be a good idea to put just the name of the institution within tags, like so: `<institution>Princeton</institution>'s`

2021-03-31 15:21 UTC, melissabreynolds commented on _posts/QueerGraduateCaucus.md
> +			<authority>professionals expert in transgender medicine</authority>.
Would this be an `<authority>` in the sense that you've used it elsewhere? I see that tag used mostly for laws and policy, and I wonder if this might be better represented with `<resource>` or `<aid>` since that is what these healthcare professionals are meant to provide. Would these professionals not also be `<persons>`? You would probably want to double tag then, as `<persons><aid>professionals expert in transgender medicine</aid></persons>`

2021-03-31 15:21 UTC, melissabreynolds commented on _posts/QueerGraduateCaucus.md
> +			<body>programs</body>, and
I'm not sure I understand the purpose of the `<body>` tag specifically--does it denote only a body on campus, and so "organizations" doesn't fall within that category? How do you imagine a researcher thinking about what a "body" means in this letter in order to understand how activism is working on campus to negotiate across power structures?

2021-03-31 15:21 UTC, melissabreynolds commented on _posts/QueerGraduateCaucus.md
> +			<authority>
Wouldn't you need a `<persons>` tag here too?

2021-03-31 15:21 UTC, melissabreynolds commented on _posts/QueerGraduateCaucus.md
> +				<body>Fields Center</body>,
Now I'm really not sure I understand how the `<body>` tag is working in this structure--it can be both "student" and "Fields Center"? Would "Fields Center" not be an `<org>`?

2021-03-31 15:21 UTC, melissabreynolds commented on _posts/QueerGraduateCaucus.md
> +				<comm>identity-based student</comm> organizations."
How are you determining the difference between `<comm>` and `<body>` and `<org>` here? Would it not be better to have one larger category that is inflected with ids? Like `<comm type="student">` or `<body type="student org">`?

2021-03-31 15:21 UTC, melissabreynolds commented on _posts/QueerGraduateCaucus.md
> +			<bod>undergraduate students
There is a misspelled tag here: `<bod>` for `<body>`

2021-03-31 15:21 UTC, melissabreynolds commented on _posts/QueerGraduateCaucus.md
> +				<body>graduate student </body>leaders
Space here between student and tag!

2021-03-31 15:21 UTC, melissabreynolds commented on _posts/QueerGraduateCaucus.md
> +		</demand4>
You would want to close the `<demand>` tag immediately after the `</comm>` tag. If you were creating this as a real XML markup file, you would write a program to ask a computer to for specific tags and return the information between those tags which is why you wouldn't want to have spaces there.

2021-03-31 15:21 UTC, melissabreynolds commented on _posts/QueerGraduateCaucus.md
> +            Ariana Myers,
`<persons>` tag?

2021-03-31 15:21 UTC, melissabreynolds commented on _posts/QueerGraduateCaucus.md
> +* *Body* calls attention to organizational structures of people that make up the institution and other organizations; bodies indicate dialogue and engagement
Body seems to function as a kind of umbrella category that can then be subdivided into institution, organizations, and community, but that isn't how it works within the document as you've encoded it. If `<body>` is an umbrella tag, then all of these other designations would need to be child elements of the parent body rather than siblings.

2021-04-02 14:34 UTC, melissabreynolds approved these changes

2021-04-02 14:34 UTC, merged

2021-04-02 14:35 UTC, p-biondi commented
Deleted 124-169, renamed document to fit conventions, and added the excerpt separator!