Paul louis biondi digital tools 4
HUM-331-Princeton/HUM-331-Princeton.github.io pull request #69
Opened 2021-04-20 14:47 UTC by p-biondi

2021-04-21 15:16 UTC, melissabreynolds requested changes
Paul-Louis,

I really like your choice of data set for this project, and you are absolutely right that Disney in the early 2000s to the early 2010s operated somewhat like the studio system of the silent film era that we analyzed in class. This is a really interesting analysis of the multi-media efforts by Disney to promote youth celebrities prior to the advent of social media and the ubiquity of YouTube. As you can see from my comments, you have a couple of technical issues with the mechanics of your links that needs fixing prior to my merging your post. I'll go over these issues a bit in class today because you were not the only person to use the incorrect image link in your post. Your use of Cytoscape, however, looks spot on, and it seems like your visualization of these networks allowed you to draw conclusions about phases of Disney celebrity-making that might not have been possible without this network analysis. 

Grade: A-

After you make those changes to the image URLs, let me know if I can go ahead and merge your post to the site.

2021-04-21 15:16 UTC, melissabreynolds commented on _posts/2021-04-19-Disney.md
> +![Disney Network](https://github.com/HUM-331-Princeton/HUM-331-Princeton.github.io/blob/8f0d3c559d08a8dbcfb9c370fff68927223881bc/images/Cytoscape%20Disney%20Network.png)
These links won't work to display your images because they are the links to the GitHub page file where the image is stored, rather than the link to the image itself. If you're going to host these images in our shared GitHub repository, then you should follow the link protocols outlined in the "Web Development Cheat Sheet." You would need to rename your image file to remove spaces, like "Cytoscape-Disney-Network" and then you could code your image into the post like so:

`![Disney Network]( {{source.baseurl }}/images/Cytoscape-Disney-Network.png)`

This tells your server to search the root directory `{{ site.baseurl }}` in the folder `/images` to find the file `Cytoscape-Disney-Network.png`.

Alternatively, if you don't want to do that, you could simply host these images in your own personal repository anywhere in GitHub, and then right click the image to find the image address. As it is now, you've used the links to the GitHub repository files rather than the links to the images themselves here, which means the images won't display correctly. I followed the links to the pages where your images are hosted, and right clicked the first image to get the following image URL: `https://github.com/HUM-331-Princeton/HUM-331-Princeton.github.io/blob/8f0d3c559d08a8dbcfb9c370fff68927223881bc/images/Cytoscape%20Disney%20Network.png?raw=true`

That would be the URL you'd use to make the image display in your post. Most image URLs will end with `raw=true`, so that's a good way to know that you've used the right URL. 

If you author your posts in Atom, you can also always key in "Control + Shift + M" to bring up a Markdown viewer that renders your code as it will appear on the blog. 

- [ ] Before I can merge your posts into the blog, I'll need you to update these image URLs with correct versions so that we can see your beautiful network visualizations!

2021-04-21 15:16 UTC, melissabreynolds commented on _posts/2021-04-19-Disney.md
> +You can view the Google Sheet I used to create the Cytoscape network [here](https://docs.google.com/spreadsheets/d/1TbMeS3ywwoJoHnECsWKLkGhLXs2MVqlPI1LUds8ct0A/edit#gid=0)
I followed the link and was denied access! Be sure to share your file and change the settings so that all people can view it.

2021-04-22 01:16 UTC, p-biondi commented
I have fixed the images. I

2021-04-22 01:21 UTC, p-biondi commented
I have fixed the images by placing them in my repository and copying the link address into the post

2021-04-22 13:16 UTC, melissabreynolds approved these changes

2021-04-22 13:16 UTC, merged