Amna amin digital tools 4
HUM-331-Princeton/HUM-331-Princeton.github.io pull request #72
Opened 2021-04-22 16:50 UTC by amnaa329

2021-04-23 17:56 UTC, melissabreynolds requested changes
Amna,

You've done a nice job with your network analysis, and my son will thank you for your choice of data set, as he is a Marvel superfan. I think it's also interesting that your assumption was that women wouldn't be featured as prominently or as frequently in these superhero movies, but in fact your network has shown that they were. Are there conclusions you could draw from that which would comment on the way we, as a culture, conceive of superheroes? Does it matter that Gwyneth Paltrow's character is in a traditional, relatively feminized role as a supporting, secretary-type, and that she is one of the most frequently represented female actors? Just some thoughts about how this network could be interpreted to lead us to new conclusions about representation within the Marvel Universe.

Be sure to edit your image URL with the correct one (see comment), and when you've done so, let me know if you'd like me to merge the post to the site.

Grade: A-

2021-04-23 17:56 UTC, melissabreynolds commented on _posts/2021-4-19-Actors-in-the-MCU.md
> +![Network Image](https://github.com/amnaa329/HUM-331-Princeton.github.io/blob/67ffdaff0c4d19b8b38f68639909ae57947d39eb/images/Network%20Image.png)
You're going to need to change this URL from the URL for your GitHub repository file to the URL for hte image itself (https://github.com/amnaa329/HUM-331-Princeton.github.io/blob/67ffdaff0c4d19b8b38f68639909ae57947d39eb/images/Network%20Image.png?raw=true).

2021-04-26 07:44 UTC, amnaa329 commented
Hi Professor Reynolds,

I fixed the image link so it should be good to merge to the website!

Best,
Amna

On Fri, Apr 23, 2021 at 1:57 PM Melissa Reynolds ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Amna,
>
> You've done a nice job with your network analysis, and my son will thank
> you for your choice of data set, as he is a Marvel superfan. I think it's
> also interesting that your assumption was that women wouldn't be featured
> as prominently or as frequently in these superhero movies, but in fact your
> network has shown that they were. Are there conclusions you could draw from
> that which would comment on the way we, as a culture, conceive of
> superheroes? Does it matter that Gwyneth Paltrow's character is in a
> traditional, relatively feminized role as a supporting, secretary-type, and
> that she is one of the most frequently represented female actors? Just some
> thoughts about how this network could be interpreted to lead us to new
> conclusions about representation within the Marvel Universe.
>
> Be sure to edit your image URL with the correct one (see comment), and
> when you've done so, let me know if you'd like me to merge the post to the
> site.
>
> Grade: A-
> ------------------------------
>
> In _posts/2021-4-19-Actors-in-the-MCU.md
> <https://github.com/HUM-331-Princeton/HUM-331-Princeton.github.io/pull/72#discussion_r619397973>
> :
>
> > +For instance, I expected the Avengers movies to have a lot of actors, and I expected those actors to have also been in other MCU movies. I wanted to investigate that
> +question since the MCU is one of the biggest and impactful franchises in the modern day. Thus, the actors cast in the movies, especially the ones who appear most frequently, are influential celebrities.
> +Additionally, I thought it was interesting to see actors and the movies they were cast in during the silent era, and examining actors in the MCU seemed like the modern day equivalent.
> +
> +The most interesting nodes to me were the avenger film nodes since those movies had the largest casts since they were bigger ensemble films.
> +The most interesting edges were between the most popular actors like Robert Downey, Mark Ruffalo, and Scarlett Johansson, especially since these actors sometimes appeared in movies that were not avengers movies or movies where they were the star.
> +For instance, Robert Downey had an interesting edge between himself and the Spiderman movie. Similarly, Mark Ruffalo had an edge between himself and Thor Ragnarok.
> +These nodes are signficant since they showcase two important aspects of the narrative of the research. The first is that it shows how certain actors and characters are popular so the MCU chooses to involve them in more projects.
> +The second is that certain characters are important instigators and features of multiple stories. For example, Robert Downey as Iron Man is important for helping Spider Man become a hero.
> +
> +I was a bit surprised to see the amount of female characters cast in multiple films. For instance, I was surprised to see that Gwenyth Paltrow was in so many movies since I did not expect a hero's love interest to be important enough to cast in a lot of films.
> +I was also surprised to see that Scarlett Johansson was cast in as many films as she was especially since some of them were not Avengers ensemble movies. For instance, she was in one of the Iron Man movies.
> +I think this aspect could demonstrate that the MCU wants to include more female characters, but they use the same few in multiple films.
> +
> +# Network Image
> +![Network Image](https://github.com/amnaa329/HUM-331-Princeton.github.io/blob/67ffdaff0c4d19b8b38f68639909ae57947d39eb/images/Network%20Image.png)
>
> You're going to need to change this URL from the URL for your GitHub
> repository file to the URL for hte image itself (
> https://github.com/amnaa329/HUM-331-Princeton.github.io/blob/67ffdaff0c4d19b8b38f68639909ae57947d39eb/images/Network%20Image.png?raw=true
> ).
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/HUM-331-Princeton/HUM-331-Princeton.github.io/pull/72#pullrequestreview-643534827>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQ3RGKB2XHKT3RBCZMB4U33TKGYHNANCNFSM43M3KBXA>
> .
>

2021-04-26 14:37 UTC, melissabreynolds approved these changes

2021-04-26 14:38 UTC, merged